$ErrorActionPreference = 'Stop'
$siteRoot = Split-Path -Parent $PSScriptRoot
$workbookFile = Get-ChildItem -LiteralPath $siteRoot -Filter '*.xlsx' | Where-Object { $_.Name -notlike '~$*' } | Select-Object -First 1
if (-not $workbookFile) { throw 'Project workbook not found.' }
$outputPath = Join-Path $siteRoot 'projects-data.js'
$enabledMarker = [string][char]26159
$fullWidthSemicolon = [string][char]65307

Add-Type -AssemblyName System.IO.Compression.FileSystem

function Read-ZipText($zip, $entryName) {
    $entry = $zip.GetEntry($entryName)
    if (-not $entry) { return $null }
    $reader = New-Object System.IO.StreamReader($entry.Open())
    try { return $reader.ReadToEnd() } finally { $reader.Dispose() }
}

function Get-ColumnNumber([string]$cellReference) {
    $letters = ([regex]::Match($cellReference, '^[A-Z]+')).Value
    $number = 0
    foreach ($character in $letters.ToCharArray()) {
        $number = ($number * 26) + ([int][char]$character - [int][char]'A' + 1)
    }
    return $number
}

function Get-CellText($cell, $sharedStrings) {
    $type = [string]$cell.GetAttribute('t')
    if ($type -eq 'inlineStr') {
        $nodes = $cell.SelectNodes("./*[local-name()='is']//*[local-name()='t']")
        return (($nodes | ForEach-Object { $_.InnerText }) -join '')
    }
    $valueNode = $cell.SelectSingleNode("./*[local-name()='v']")
    if (-not $valueNode) { return '' }
    $value = [string]$valueNode.InnerText
    if ($type -eq 's') {
        $index = [int]$value
        if ($index -ge 0 -and $index -lt $sharedStrings.Count) { return [string]$sharedStrings[$index] }
    }
    return $value
}

$zip = [System.IO.Compression.ZipFile]::OpenRead($workbookFile.FullName)
try {
    $sharedStrings = @()
    $sharedXmlText = Read-ZipText $zip 'xl/sharedStrings.xml'
    if ($sharedXmlText) {
        [xml]$sharedXml = $sharedXmlText
        $sharedStrings = @($sharedXml.SelectNodes("//*[local-name()='si']") | ForEach-Object {
            (($_.SelectNodes(".//*[local-name()='t']") | ForEach-Object { $_.InnerText }) -join '')
        })
    }

    [xml]$sheetXml = Read-ZipText $zip 'xl/worksheets/sheet1.xml'
    $rows = $sheetXml.SelectNodes("//*[local-name()='sheetData']/*[local-name()='row']")
    $projects = @()

    foreach ($row in $rows) {
        $rowNumber = [int]$row.GetAttribute('r')
        if ($rowNumber -eq 1) { continue }
        $values = @{}
        foreach ($cell in $row.SelectNodes("./*[local-name()='c']")) {
            $column = Get-ColumnNumber ([string]$cell.GetAttribute('r'))
            $values[$column] = Get-CellText $cell $sharedStrings
        }

        $enabled = ([string]$values[1]).Trim()
        $titleZh = [string]$values[4]
        if ([string]::IsNullOrWhiteSpace($titleZh)) { continue }
        if ($enabled -notin @($enabledMarker, 'TRUE', 'True', 'true', '1', 'YES', 'Yes', 'yes')) { continue }

        $rawId = ([string]$values[3]).Trim()
        if ($rawId -match '^\d+$') { $projectId = ([int]$rawId).ToString('00') } else { $projectId = $rawId }
        $rawOrder = [string]$values[2]
        $order = if ([string]::IsNullOrWhiteSpace($rawOrder)) { $rowNumber - 1 } else { [int][double]$rawOrder }
        $rawImages = [string]$values[13]
        $images = @()
        if (-not [string]::IsNullOrWhiteSpace($rawImages)) {
            $splitPattern = ';|' + $fullWidthSemicolon
            $images = @($rawImages -split $splitPattern | ForEach-Object { $_.Trim().Replace('\', '/') } | Where-Object { $_ })
        }

        $projects += [ordered]@{
            id = $projectId
            order = $order
            zh = $titleZh.Trim()
            en = ([string]$values[5]).Trim()
            tag = ([string]$values[6]).Trim()
            year = ([string]$values[7]).Trim()
            tools = ([string]$values[8]).Trim()
            descriptionZh = ([string]$values[9]).Trim()
            descriptionEn = ([string]$values[10]).Trim()
            video = ([string]$values[11]).Trim().Replace('\', '/')
            poster = ([string]$values[12]).Trim().Replace('\', '/')
            images = $images
            placeholder = ([string]$values[14]).Trim().Replace('\', '/')
        }
    }

    $projects = @($projects | Sort-Object order)
    $json = ConvertTo-Json -InputObject $projects -Depth 5 -Compress
    $header = '/* Generated from the project workbook. Do not edit this file manually. */' + [Environment]::NewLine
    $content = $header + 'window.PORTFOLIO_PROJECTS = ' + $json + ';' + [Environment]::NewLine
    [System.IO.File]::WriteAllText($outputPath, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Updated $($projects.Count) projects." -ForegroundColor Green
    Write-Host "Output: $outputPath"
}
finally {
    $zip.Dispose()
}
